title: Korver AI Solutions
email: hello@korver.ai
description: Korver AI Solutions develops purposeful software and research-driven projects at the intersection of technology and real-world impact.
baseurl: ""
url: "https://korver.ai"
instagram_username: korver.ai

# Collections
collections:
  projects_en:
    output: true
    permalink: /en/projects/:name/
  projects_nl:
    output: true
    permalink: /nl/projects/:name/

# Build Settings
remote_theme: null
plugins:
  - jekyll-feed

# Language Settings
defaults:
  - scope:
      path: "en"
    values:
      lang: en
  - scope:
      path: "nl"
    values:
      lang: nl
  - scope:
      path: ""
      type: projects_en
    values:
      lang: en
      layout: project
  - scope:
      path: ""
      type: projects_nl
    values:
      lang: nl
      layout: project

# Exclude from Processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md