title: Korver AI Solutions
email: hello@korver.ai
description: Korver AI Solutions develops purposeful software and research-driven projects at the intersection of technology and real-world impact.
baseurl: ""
url: "https://korver.ai"
instagram_username: korver.ai

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Build settings
remote_theme: null
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
